# Generated by Django 4.2.9 on 2024-04-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Bugatti', 'Bugatti'), ('Mercedes', 'Mercedes'), ('Range Rover', 'Range Rover')], max_length=30)),
                ('product_image', models.ImageField(upload_to='CarImages')),
            ],
        ),
    ]
